apiVersion: vitistack.io/v1alpha1
kind: NetworkConfiguration
metadata:
  name: test-networkconfiguration
spec:
  name: test-networkconfiguration
  description: "Test Network Configuration"
  datacenterIdentifier: test-south-az1
  supervisorIdentifier: test-viti
  clusterIdentifier: test-cluster
  provider: test-provider
  networkInterfaces:
    - name: testeth1
      dhcpReserved: false
      dns: []
      ipv4Addresses: []
      ipv4Gateway: ""
      ipv4Subnet: ""
      macAddress: "00:02:12:34:56:78"
      vlan: ""
      ipv6Addresses: []
      ipv6Gateway: ""
      ipv6Subnet: ""
