apiVersion: v1
kind: Service
metadata:
  name: {{ include "kea-operator.fullname" . }}
  labels:
    {{- include "kea-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9995
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "kea-operator.selectorLabels" . | nindent 4 }}
